# Generated by Django 6.0.7 on 2026-07-23 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lyric_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='catalog.lyricversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_analysis_jobs', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='catalog.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('key_themes', models.JSONField(default=list)),
                ('model_identifier', models.CharField(max_length=255)),
                ('prompt_version', models.CharField(max_length=100)),
                ('provider_metadata', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisjob')),
                ('lyric_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='catalog.lyricversion')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='catalog.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
