# Generated by Django 6.0.7 on 2026-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="citations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="detailed_analysis",
            field=models.JSONField(default=dict),
        ),
    ]
