# Generated by Django 6.0.7 on 2026-07-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricline',
            name='is_separator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lyricline',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
